import os
from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta
from medicines.models import Medicine

class Command(BaseCommand):
    help = 'Seeds database with realistic medicines and substitute pairs'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding medicines data...')

        today = timezone.now().date()
        future_date_1 = today + timedelta(days=365 * 2)
        future_date_2 = today + timedelta(days=365 * 3)
        future_date_short = today + timedelta(days=180)

        medicines_data = [
            # 1. FEVER & PAIN (Paracetamol 650mg Tablet)
            {
                'name': 'Dolo 650',
                'generic_name': 'Paracetamol',
                'composition': 'Paracetamol',
                'strength': '650mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Micro Labs Ltd',
                'price': 31.00,
                'stock_quantity': 180,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Fever & Pain Relief',
                'description': 'Trusted antipyretic and pain reliever tablet for fever, head aches, muscular aches and flu symptoms.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 140
            },
            {
                'name': 'Calpol 650',
                'generic_name': 'Paracetamol',
                'composition': 'Paracetamol',
                'strength': '650mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'GSK Pharmaceuticals',
                'price': 33.50,
                'stock_quantity': 150,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Fever & Pain Relief',
                'description': 'Clinically proven Paracetamol 650mg tablet for high fever and body ache relief.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 95
            },
            {
                'name': 'Pacimol 650',
                'generic_name': 'Paracetamol',
                'composition': 'Paracetamol',
                'strength': '650mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Ipca Laboratories',
                'price': 18.50,
                'stock_quantity': 220,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Fever & Pain Relief',
                'description': 'Economical high quality generic Paracetamol 650mg tablet offering exact therapeutic action.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 78
            },
            {
                'name': 'Crocin 650',
                'generic_name': 'Paracetamol',
                'composition': 'Paracetamol',
                'strength': '650mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'GlaxoSmithKline Consumer',
                'price': 34.00,
                'stock_quantity': 90,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Fever & Pain Relief',
                'description': 'Fast release paracetamol 650mg formula for acute headaches and fever.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 110
            },
            {
                'name': 'Parafast 650',
                'generic_name': 'Paracetamol',
                'composition': 'Paracetamol',
                'strength': '650mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Cipla Ltd',
                'price': 14.00,
                'stock_quantity': 300,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Fever & Pain Relief',
                'description': 'Generic Jan Aushadhi equivalent pure Paracetamol 650mg for budget-conscious patients.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 60
            },

            # 2. ANTIBIOTICS (Amoxicillin + Clavulanic Acid 625mg)
            {
                'name': 'Augmentin 625 Duo',
                'generic_name': 'Amoxicillin and Potassium Clavulanate',
                'composition': 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
                'strength': '625mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'GSK India',
                'price': 225.00,
                'stock_quantity': 75,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Antibiotics & Anti-Infectives',
                'description': 'Potent broad-spectrum antibacterial medicine for bacterial respiratory, ENT, skin and dental infections.',
                'image_url': 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
                'search_count': 180
            },
            {
                'name': 'Moxikind-CV 625',
                'generic_name': 'Amoxicillin and Potassium Clavulanate',
                'composition': 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
                'strength': '625mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Mankind Pharma',
                'price': 130.00,
                'stock_quantity': 140,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Antibiotics & Anti-Infectives',
                'description': 'Cost-effective alternative with matching Amoxicillin and Clavulanate ratios for high efficacy.',
                'image_url': 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
                'search_count': 125
            },
            {
                'name': 'Clavam 625',
                'generic_name': 'Amoxicillin and Potassium Clavulanate',
                'composition': 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
                'strength': '625mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Alkem Laboratories',
                'price': 155.00,
                'stock_quantity': 110,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Antibiotics & Anti-Infectives',
                'description': 'High-standard bioequivalent antibiotic tablet for acute bacterial sinusitis and bronchitis.',
                'image_url': 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
                'search_count': 90
            },
            {
                'name': 'Novamox-CV 625',
                'generic_name': 'Amoxicillin and Potassium Clavulanate',
                'composition': 'Amoxicillin (500mg) + Clavulanic Acid (125mg)',
                'strength': '625mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Cipla Ltd',
                'price': 118.00,
                'stock_quantity': 160,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Antibiotics & Anti-Infectives',
                'description': 'Top-rated affordable substitute providing substantial savings on prescription antibiotics.',
                'image_url': 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
                'search_count': 85
            },

            # 3. CARDIOVASCULAR & HYPERTENSION (Telmisartan 40mg)
            {
                'name': 'Telma 40',
                'generic_name': 'Telmisartan',
                'composition': 'Telmisartan',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Glenmark Pharmaceuticals',
                'price': 148.00,
                'stock_quantity': 130,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'First line Angiotensin Receptor Blocker (ARB) prescribed for chronic hypertension and heart protection.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 160
            },
            {
                'name': 'Telpres 40',
                'generic_name': 'Telmisartan',
                'composition': 'Telmisartan',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Abbott Healthcare',
                'price': 82.00,
                'stock_quantity': 175,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'Reliable Telmisartan 40mg tablet from Abbott with equal clinical blood pressure reduction.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 92
            },
            {
                'name': 'Telmikind 40',
                'generic_name': 'Telmisartan',
                'composition': 'Telmisartan',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Mankind Pharma',
                'price': 65.00,
                'stock_quantity': 210,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'Budget-friendly daily antihypertensive tablet offering over 55% savings compared to market leader.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 115
            },
            {
                'name': 'Telvas 40',
                'generic_name': 'Telmisartan',
                'composition': 'Telmisartan',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Aristo Pharmaceuticals',
                'price': 72.00,
                'stock_quantity': 140,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'High-bioavailability telmisartan 40mg for essential hypertension therapy.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 64
            },

            # 4. GASTROINTESTINAL & ACIDITY (Pantoprazole 40mg)
            {
                'name': 'Pan 40',
                'generic_name': 'Pantoprazole',
                'composition': 'Pantoprazole',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Alkem Laboratories',
                'price': 160.00,
                'stock_quantity': 160,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'Proton pump inhibitor (PPI) providing relief from acid reflux, heartburn, GERD, and stomach ulcers.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 175
            },
            {
                'name': 'Pantocid 40',
                'generic_name': 'Pantoprazole',
                'composition': 'Pantoprazole',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Sun Pharmaceutical',
                'price': 168.00,
                'stock_quantity': 120,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'Fast-acting enteric-coated pantoprazole 40mg for gastro-esophageal reflux disease.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 130
            },
            {
                'name': 'Pantodac 40',
                'generic_name': 'Pantoprazole',
                'composition': 'Pantoprazole',
                'strength': '40mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Zydus Cadila',
                'price': 98.00,
                'stock_quantity': 190,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'Trusted generic alternative for controlling gastric acid secretion with 40% cost advantage.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 105
            },
            {
                'name': 'Panto-DSR 40',
                'generic_name': 'Pantoprazole and Domperidone',
                'composition': 'Pantoprazole (40mg) + Domperidone (30mg)',
                'strength': '40mg+30mg',
                'dosage_form': 'Capsule',
                'manufacturer': 'Torrent Pharma',
                'price': 195.00,
                'stock_quantity': 85,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'Dual-action sustained release capsule for severe GERD with nausea and bloating.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 140
            },
            {
                'name': 'Pan-D Capsule',
                'generic_name': 'Pantoprazole and Domperidone',
                'composition': 'Pantoprazole (40mg) + Domperidone (30mg)',
                'strength': '40mg+30mg',
                'dosage_form': 'Capsule',
                'manufacturer': 'Alkem Laboratories',
                'price': 210.00,
                'stock_quantity': 100,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'Leading branded combination for reflux oesophagitis and dysmotility symptoms.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 155
            },
            {
                'name': 'Dompan SR',
                'generic_name': 'Pantoprazole and Domperidone',
                'composition': 'Pantoprazole (40mg) + Domperidone (30mg)',
                'strength': '40mg+30mg',
                'dosage_form': 'Capsule',
                'manufacturer': 'Medley Pharma',
                'price': 125.00,
                'stock_quantity': 150,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Gastrointestinal & Acidity',
                'description': 'High value substitute for Pan-D saving over 40% per strip.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 72
            },

            # 5. DIABETES CARE (Metformin 500mg Tablet)
            {
                'name': 'Glycomet 500',
                'generic_name': 'Metformin Hydrochloride',
                'composition': 'Metformin',
                'strength': '500mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'USV Private Ltd',
                'price': 44.00,
                'stock_quantity': 250,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Diabetes Care',
                'description': 'Gold standard biguanide oral antidiabetic medication for Type 2 Diabetes Mellitus control.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 190
            },
            {
                'name': 'Metfor 500',
                'generic_name': 'Metformin Hydrochloride',
                'composition': 'Metformin',
                'strength': '500mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Cipla Ltd',
                'price': 25.00,
                'stock_quantity': 310,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Diabetes Care',
                'description': 'Generic Metformin 500mg tablet for daily long-term glycemic index management.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 110
            },
            {
                'name': 'Gluconorm 500',
                'generic_name': 'Metformin Hydrochloride',
                'composition': 'Metformin',
                'strength': '500mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Lupin Pharmaceuticals',
                'price': 38.00,
                'stock_quantity': 180,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Diabetes Care',
                'description': 'Extended glycemic stabilization tablet from Lupin with proven clinical tolerability.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 82
            },
            {
                'name': 'Januvia 100',
                'generic_name': 'Sitagliptin',
                'composition': 'Sitagliptin',
                'strength': '100mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'MSD Pharmaceuticals',
                'price': 420.00,
                'stock_quantity': 60,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Diabetes Care',
                'description': 'DPP-4 inhibitor tablet regulating insulin and glucagon levels post-meals.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 115
            },
            {
                'name': 'Zita 100',
                'generic_name': 'Sitagliptin',
                'composition': 'Sitagliptin',
                'strength': '100mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Glenmark Pharmaceuticals',
                'price': 190.00,
                'stock_quantity': 110,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Diabetes Care',
                'description': 'Exact bioequivalent DPP-4 inhibitor Sitagliptin 100mg at over 50% discount.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 94
            },

            # 6. RESPIRATORY & ALLERGY (Levocetirizine + Montelukast)
            {
                'name': 'Montair-LC',
                'generic_name': 'Montelukast and Levocetirizine',
                'composition': 'Levocetirizine (5mg) + Montelukast (10mg)',
                'strength': '5mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Cipla Ltd',
                'price': 212.00,
                'stock_quantity': 140,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Respiratory & Allergy',
                'description': 'Dual antihistamine and leukotriene receptor antagonist for allergic rhinitis and asthma prophylaxis.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 210
            },
            {
                'name': 'Montek-LC',
                'generic_name': 'Montelukast and Levocetirizine',
                'composition': 'Levocetirizine (5mg) + Montelukast (10mg)',
                'strength': '5mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Sun Pharma',
                'price': 198.00,
                'stock_quantity': 160,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Respiratory & Allergy',
                'description': 'Trusted anti-allergic combination tablet controlling sneezing, runny nose, and breathlessness.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 145
            },
            {
                'name': 'Telekast-L',
                'generic_name': 'Montelukast and Levocetirizine',
                'composition': 'Levocetirizine (5mg) + Montelukast (10mg)',
                'strength': '5mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Lupin Ltd',
                'price': 145.00,
                'stock_quantity': 190,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Respiratory & Allergy',
                'description': 'High savings substitute with identical active salts and dosage strength for chronic allergy.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 120
            },
            {
                'name': 'Levocet-M',
                'generic_name': 'Montelukast and Levocetirizine',
                'composition': 'Levocetirizine (5mg) + Montelukast (10mg)',
                'strength': '5mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Hetero Healthcare',
                'price': 110.00,
                'stock_quantity': 220,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Respiratory & Allergy',
                'description': 'Affordable generic substitute saving nearly 50% on seasonal allergy prescriptions.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 88
            },

            # 7. CHOLESTEROL & LIPID CARE (Atorvastatin 10mg)
            {
                'name': 'Atorva 10',
                'generic_name': 'Atorvastatin',
                'composition': 'Atorvastatin',
                'strength': '10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Zydus Cadila',
                'price': 115.00,
                'stock_quantity': 135,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'HMG-CoA reductase inhibitor (Statin) used for lowering LDL cholesterol and triglycerides.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 130
            },
            {
                'name': 'Lipitor 10',
                'generic_name': 'Atorvastatin',
                'composition': 'Atorvastatin',
                'strength': '10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Pfizer India',
                'price': 145.00,
                'stock_quantity': 80,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'Original innovator brand atorvastatin tablet for cardiovascular risk reduction.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 95
            },
            {
                'name': 'Storvas 10',
                'generic_name': 'Atorvastatin',
                'composition': 'Atorvastatin',
                'strength': '10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Sun Pharma',
                'price': 85.00,
                'stock_quantity': 190,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'High-repute lipid lowering substitute providing substantial long-term savings.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 110
            },
            {
                'name': 'Atocor 10',
                'generic_name': 'Atorvastatin',
                'composition': 'Atorvastatin',
                'strength': '10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Dr Reddys Laboratories',
                'price': 62.00,
                'stock_quantity': 240,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Cardiovascular & Hypertension',
                'description': 'Budget-friendly pure Atorvastatin 10mg from Dr Reddys with 55% savings.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 76
            },

            # 8. VITAMINS & NUTRITIONAL (Vitamin D3 60k IU Capsule / Drops)
            {
                'name': 'Calcirol 60K',
                'generic_name': 'Cholecalciferol (Vitamin D3)',
                'composition': 'Cholecalciferol',
                'strength': '60000 IU',
                'dosage_form': 'Capsule',
                'manufacturer': 'Cadila Healthcare',
                'price': 135.00,
                'stock_quantity': 180,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Vitamins & Minerals',
                'description': 'High potency weekly oral vitamin D3 soft gelatin capsule for bone density and calcium absorption.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 165
            },
            {
                'name': 'Uprise-D3 60K',
                'generic_name': 'Cholecalciferol (Vitamin D3)',
                'composition': 'Cholecalciferol',
                'strength': '60000 IU',
                'dosage_form': 'Capsule',
                'manufacturer': 'Alkem Laboratories',
                'price': 142.00,
                'stock_quantity': 150,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Vitamins & Minerals',
                'description': 'Convenient weekly cholecalciferol capsule treating Vitamin D deficiency and fatigue.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 135
            },
            {
                'name': 'D-Rise 60K',
                'generic_name': 'Cholecalciferol (Vitamin D3)',
                'composition': 'Cholecalciferol',
                'strength': '60000 IU',
                'dosage_form': 'Capsule',
                'manufacturer': 'USV Ltd',
                'price': 88.00,
                'stock_quantity': 220,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Vitamins & Minerals',
                'description': 'Direct therapeutic substitute for Vitamin D3 60000 IU with nearly 40% cost reduction.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 92
            },
            {
                'name': 'Depura 60K Sugar Free',
                'generic_name': 'Cholecalciferol (Vitamin D3)',
                'composition': 'Cholecalciferol',
                'strength': '60000 IU',
                'dosage_form': 'Syrup',
                'manufacturer': 'Sanofi India',
                'price': 110.00,
                'stock_quantity': 90,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Vitamins & Minerals',
                'description': 'Oral liquid formulation solution 60000 IU for elderly or patients with swallowing difficulty.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 70
            },

            # 9. DERMATOLOGY & TOPICAL (Clotrimazole 1% Cream)
            {
                'name': 'Candid Cream',
                'generic_name': 'Clotrimazole',
                'composition': 'Clotrimazole',
                'strength': '1% w/w',
                'dosage_form': 'Cream',
                'manufacturer': 'Glenmark Pharmaceuticals',
                'price': 118.00,
                'stock_quantity': 100,
                'expiry_date': future_date_1,
                'prescription_required': False,
                'disease_category': 'Dermatology & Skin Care',
                'description': 'Broad spectrum topical antifungal cream for ringworm, athlete foot, and fungal skin infections.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 110
            },
            {
                'name': 'Canesten Cream',
                'generic_name': 'Clotrimazole',
                'composition': 'Clotrimazole',
                'strength': '1% w/w',
                'dosage_form': 'Cream',
                'manufacturer': 'Bayer Pharmaceuticals',
                'price': 130.00,
                'stock_quantity': 80,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Dermatology & Skin Care',
                'description': 'High-efficacy topical clotrimazole 1% w/w cream soothing fungal itching and redness.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 85
            },
            {
                'name': 'Clocip Cream',
                'generic_name': 'Clotrimazole',
                'composition': 'Clotrimazole',
                'strength': '1% w/w',
                'dosage_form': 'Cream',
                'manufacturer': 'Cipla Ltd',
                'price': 65.00,
                'stock_quantity': 150,
                'expiry_date': future_date_2,
                'prescription_required': False,
                'disease_category': 'Dermatology & Skin Care',
                'description': 'Top-rated affordable generic clotrimazole 1% cream with 50% price savings.',
                'image_url': 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
                'search_count': 92
            },

            # 10. NEUROLOGICAL & PAIN (Gabapentin + Methylcobalamin)
            {
                'name': 'Gabapin NT',
                'generic_name': 'Gabapentin and Nortriptyline',
                'composition': 'Gabapentin (400mg) + Nortriptyline (10mg)',
                'strength': '400mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Intas Pharmaceuticals',
                'price': 280.00,
                'stock_quantity': 70,
                'expiry_date': future_date_1,
                'prescription_required': True,
                'disease_category': 'Neurological Care',
                'description': 'Indicated for diabetic neuropathic pain, sciatica, and post-herpetic neuralgia relief.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 90
            },
            {
                'name': 'Gabaneuron NT',
                'generic_name': 'Gabapentin and Nortriptyline',
                'composition': 'Gabapentin (400mg) + Nortriptyline (10mg)',
                'strength': '400mg+10mg',
                'dosage_form': 'Tablet',
                'manufacturer': 'Aristo Pharmaceuticals',
                'price': 175.00,
                'stock_quantity': 95,
                'expiry_date': future_date_2,
                'prescription_required': True,
                'disease_category': 'Neurological Care',
                'description': 'Direct generic substitute for neuropathic nerve pain management saving over 35%.',
                'image_url': 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
                'search_count': 68
            }
        ]

        count_created = 0
        count_updated = 0

        for item in medicines_data:
            med, created = Medicine.objects.update_or_create(
                name=item['name'],
                strength=item['strength'],
                dosage_form=item['dosage_form'],
                defaults=item
            )
            if created:
                count_created += 1
            else:
                count_updated += 1

        self.stdout.write(self.style.SUCCESS(f"Seeding completed successfully! Created: {count_created}, Updated: {count_updated} medicines."))
