# Generated by Django 5.1.15 on 2026-09-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('composition', models.CharField(db_index=True, max_length=255)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('prescription_required', models.BooleanField(default=False)),
                ('disease_category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('search_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['composition', 'strength', 'dosage_form'], name='medicines_m_composi_246ac6_idx'), models.Index(fields=['disease_category'], name='medicines_m_disease_b1ccc0_idx')],
            },
        ),
    ]
